const hoteles = [
    {
        id: "hotel1",
        nombre: "Hotel Bidasoa",
        region: "Metropolitana",
        calificacion: 5,
        precio: 144000,
        imagen: [
            "img/bidasoa2.jpg",
            "img/bidasoa3.jpg",
        ],
    },
    {
        id: "hotel2",
        nombre: "Hillside Hotel",
        region: "Metropolitana",
        calificacion: 4,
        precio: 110000,
        imagen: [
            "img/hillside1.jpg",
            "img/hillside2.jpg",
            "img/hillside3.jpg",
        ],
    },  
    {
        id: "hotel3",
        nombre: "Carmenere Hotel",
        region: "Metropolitana",
        calificacion: 5,
        precio: 94000,
        imagen: [
            "img/carmenere1.jpg",
            "img/carmenere2.jpg",
            "img/carmenere3.jpg",
        ],
    },
    {
        id: "hotel4",
        nombre: "Hotel Foresta",
        region: "Metropolitana",
        calificacion: 3,
        precio: 77978,
        imagen: [
            "img/foresta1.jpg",
            "img/foresta2.jpg",
            "img/foresta3.jpg",
        ],
    }, 
    {
        id: "hotel5",
        nombre: "Hotel Bonaparte Boutique",
        region: "Metropolitana",
        calificacion: 4,
        precio: 94613,
        imagen: [
            "img/bonaparte1.jpg",
            "img/bonaparte2.jpg",
            "img/bonaparte3.jpg",
        ],
    },
    {
        id: "hotel6",
        nombre: "Hotel ibis Santiago Providencia",
        region: "Metropolitana",
        calificacion: 3,
        precio: 71222,
        imagen: [
            "img/ibis1.jpg",
            "img/ibis2.jpg",
            "img/ibis3.jpg",
        ],
    }, 
    {
        id: "hotel7",
        nombre: "Hotel Luciano K",
        region: "Metropolitana",
        calificacion: 4,
        precio: 149255,
        imagen: [
            "img/luciano1.jpg",
            "img/luciano2.jpg",
            "img/luciano3.jpg",
        ],
    }, 
    {
        id: "hotel8",
        nombre: "Hotel Noi Vitacura",
        region: "Metropolitana",
        calificacion: 5,
        precio: 265124,
        imagen: [
            "img/noi1.jpg",
            "img/noi2.jpg",
            "img/noi3.jpg",
        ],
    },
    {
        id: "hotel9",
        nombre: "Hotel Pullman Santiago Vitacura",
        region: "Metropolitana",
        calificacion: 5,
        precio: 104037,
        imagen: [
            "img/pullman1.jpg",
            "img/pullman2.jpg",
            "img/pullman3.jpg",
        ],
    },
    {
        id: "hotel10",
        nombre: "Hotel Plaza San Francisco",
        region: "Metropolitana",
        calificacion: 5,
        precio: 124757,
        imagen: [
            "img/francisco1.jpg",
            "img/francisco2.jpg",
            "img/francisco3.jpg",
        ],
    },


    {
        id: "hotel11",
        nombre: "Hotel Sheraton Miramar",
        region: "Valparaíso",
        calificacion: 5,
        precio: 322010,
        imagen: [
            "img/sheraton1.jpg",
            "img/sheraton2.jpg",
            "img/sheraton3.jpg",
        ],
    },
    {
        id: "hotel12",
        nombre: "Hotel Casamata Poshtel",
        region: "Valparaíso",
        calificacion: 5,
        precio: 87878,
        imagen: [
            "img/casamata1.jpg",
            "img/casamata2.jpg",
            "img/casamata3.jpg",
        ],
    },
    {
        id: "hotel13",
        nombre: "Hotel Pullman Viña del Mar",
        region: "Valparaíso",
        calificacion: 4,
        precio: 114000,
        imagen: [
            "img/pullmanvina1.jpg",
            "img/pullmanvina2.jpg",
            "img/pullmanvina3.jpg",
        ],
    },
    {
        id: "hotel14",
        nombre: "Hotel La Blanca",
        region: "Valparaíso",
        calificacion: 4,
        precio: 85000,
        imagen: [
            "img/blanca1.jpg",
            "img/blanca2.jpg",
            "img/blanca3.jpg",
        ],
    },
    {
        id: "hotel15",
        nombre: "Columba Hotel",
        region: "Valparaíso",
        calificacion: 3,
        precio: 31000,
        imagen: [
            "img/columba1.jpg",
            "img/columba2.jpg",
            "img/columba3.jpg",
        ],
    },
    {
        id: "hotel16",
        nombre: "Hotel Vista Hermosa",
        region: "Valparaíso",
        calificacion: 3,
        precio: 44000,
        imagen: [
            "img/hermosa1.jpg",
            "img/hermosa2.jpg",
        ],
    },
    {
        id: "hotel17",
        nombre: "Hotel Valle Hermoso",
        region: "Valparaíso",
        calificacion: 4,
        precio: 21000,
        imagen: [
            "img/hermoso1.jpg",
            "img/hermoso2.jpg",
        ],
    },
    {
        id: "hotel18",
        nombre: "Hotel CasaMoro",
        region: "Valparaíso",
        calificacion: 5,
        precio: 65000,
        imagen: [
            "img/casamoro1.jpg",
            "img/casamoro2.jpg",
            "img/casamoro3.jpg",
        ],
    },  
    {
        id: "hotel19",
        nombre: "Hotel Valle Hermoso",
        region: "Valparaíso",
        calificacion: 4,
        precio: 21000,
        imagen: [
            "img/hermoso1.jpg",
            "img/hermoso2.jpg",
        ],
    }              
];
